version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: dms_postgres
    restart: always
    environment:
      POSTGRES_USER: dms_user
      POSTGRES_PASSWORD: dms_password
      POSTGRES_DB: dms_db
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
